import Head from "next/head";
import { useState } from "react";

import Header from "@/comps/header";
import Footer from "@/comps/footer";

import MarketInfo from "@/comps/infoPanel/market";
import Info from "@/comps/infoPanel/info";
import Stake from "@/comps/stake/stake";

export default function Home() {
  const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);
  const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
    useState(false);

  const closeAll = () => {
    console.log("closeAll");
    setIsNetworkSwitchHighlighted(false);
    setIsConnectHighlighted(false);
  };

  return (
    <>
      <Head>
        <title>Coin Market</title>
        <meta name="description" content="Generated by create-wc-dapp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header isNetworkSwitchHighlighted isConnectHighlighted closeAll />
      <main>
        {/* <MarketInfo /> */}
        {/* <Info /> */}
        <Stake />
      </main>
      <Footer />
    </>
  );
}
